export const dummyBuildingData = [
  {
    id: 1,
    addr: "감자시 고구마구 호박로 1번길 100 야채빌",
    todo: 10,
    inProgress: 3,
    houses: [
      {
        id: 1,
        dong: 101,
        ho: 101,
        status: "done",
        isConnected: false,
      },
      {
        id: 2,
        dong: 101,
        ho: 102,
        status: "todo",
        isConnected: true,
      },
      {
        id: 3,

        dong: 101,
        ho: 103,
        status: "done",
        isConnected: false,
      },
      {
        id: 4,

        dong: 101,
        ho: 104,
        status: "todo",
        isConnected: true,
      },
      {
        id: 5,
        dong: 101,
        ho: 105,
        status: "done",
        isConnected: false,
      },
    ],
  },
  {
    id: 2,
    addr: "토란시 감치구 돼지로 2번길 32 채소빌",
    todo: 12,
    inProgress: 3,
    houses: [
      {
        id: 6,
        dong: 201,
        ho: 101,
        status: "todo",
        isConnected: false,
      },
      {
        id: 7,
        dong: 201,
        ho: 102,
        status: "done",
        isConnected: false,
      },
      {
        id: 8,
        dong: 201,
        ho: 103,
        status: "done",
        isConnected: false,
      },
      {
        id: 9,
        dong: 201,
        ho: 104,
        status: "todo",
        isConnected: false,
      },
      {
        id: 10,
        dong: 201,
        ho: 105,
        status: "done",
        isConnected: false,
      },
    ],
  },
  {
    id: 3,
    addr: "병아리시 알알구 아리로 3번길 99 치킨빌",
    todo: 40,
    inProgress: 1,
    houses: [
      {
        id: 11,
        dong: 301,
        ho: 101,
        status: "todo",
        isConnected: false,
      },
      {
        id: 12,
        dong: 301,
        ho: 102,
        status: "todo",
        isConnected: false,
      },
      {
        id: 13,
        dong: 301,
        ho: 103,
        status: "done",
        isConnected: false,
      },
      {
        id: 14,
        dong: 301,
        ho: 104,
        status: "done",
        isConnected: false,
      },
      {
        id: 15,
        dong: 301,
        ho: 105,
        status: "todo",
        isConnected: false,
      },
    ],
  },
  {
    id: 4,
    addr: "닭시 계구 췩힌로 4번길 101",
    todo: 5,
    inProgress: 0,
    houses: [
      {
        id: 16,
        dong: 401,
        ho: 101,
        status: "done",
        isConnected: false,
      },
      {
        id: 17,
        dong: 401,
        ho: 102,
        status: "done",
        isConnected: false,
      },
      { id: 18, dong: 401, ho: 103, status: "done", isConnected: false },
      { id: 19, dong: 401, ho: 104, status: "done", isConnected: false },
      { id: 20, dong: 401, ho: 105, status: "done", isConnected: false },
    ],
  },
];

export const dummyHouseData = [
  {
    id: 1,
    dong: 101,
    ho: 101,
    status: "done",
    isConnected: false,
  },
  {
    id: 2,
    dong: 101,
    ho: 102,
    status: "todo",
    isConnected: true,
  },
  {
    id: 3,

    dong: 101,
    ho: 103,
    status: "done",
    isConnected: false,
  },
  {
    id: 4,

    dong: 101,
    ho: 104,
    status: "todo",
    isConnected: true,
  },
  {
    id: 5,
    dong: 101,
    ho: 105,
    status: "done",
    isConnected: false,
  },
  {
    id: 6,
    dong: 201,
    ho: 101,
    status: "todo",
    isConnected: false,
  },
  {
    id: 7,
    dong: 201,
    ho: 102,
    status: "done",
    isConnected: false,
  },
  {
    id: 8,
    dong: 201,
    ho: 103,
    status: "done",
    isConnected: false,
  },
  {
    id: 9,
    dong: 201,
    ho: 104,
    status: "todo",
    isConnected: false,
  },
  {
    id: 10,
    dong: 201,
    ho: 105,
    status: "done",
    isConnected: false,
  },

  {
    id: 11,
    dong: 301,
    ho: 101,
    status: "todo",
    isConnected: false,
  },
  {
    id: 12,
    dong: 301,
    ho: 102,
    status: "todo",
    isConnected: false,
  },
  {
    id: 13,
    dong: 301,
    ho: 103,
    status: "done",
    isConnected: false,
  },
  {
    id: 14,
    dong: 301,
    ho: 104,
    status: "done",
    isConnected: false,
  },
  {
    id: 15,
    dong: 301,
    ho: 105,
    status: "todo",
    isConnected: false,
  },
  {
    id: 16,
    dong: 401,
    ho: 101,
    status: "done",
    isConnected: false,
  },
  {
    id: 17,
    dong: 401,
    ho: 102,
    status: "done",
    isConnected: false,
  },
  { id: 18, dong: 401, ho: 103, status: "done", isConnected: false },
  { id: 19, dong: 401, ho: 104, status: "done", isConnected: false },
  { id: 20, dong: 401, ho: 105, status: "done", isConnected: false },
];
